controller_names:
  - fake_finger1_controller
  - fake_finger2_controller
  - fake_finger3_controller
  - fake_finger4_controller
  - fake_finger5_controller
  - fake_fingertip1_controller
  - fake_fingertip2_controller
  - fake_fingertip3_controller
  - fake_fingertip4_controller
  - fake_fingertip5_controller

fake_finger1_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - J11
    - J12
    - J13
    - J14
    - J15

fake_finger2_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - J21
    - J22
    - J23
    - J24

fake_finger3_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - J31
    - J32
    - J33
    - J34

fake_finger4_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - J41
    - J42
    - J43
    - J44

fake_finger5_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - J51
    - J52
    - J53
    - J54

fake_fingertip1_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - J15

fake_fingertip2_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - J24

fake_fingertip3_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - J34

fake_fingertip4_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - J44

fake_fingertip5_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - J54
